# Site settings
title: Matt Christian
header-img: ./img/cover.jpeg
email: matthew.bryan.christian@gmail.com

url: "http://analyticalmeanderings.github.io"
github_username:  analyticalmeanderings
linkedin: https://www.linkedin.com/in/matthew-christian-17577641

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 6
paginate_path: blog/page:num
excerpt_separator: <!--more-->
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
permalink: /blog/:title
#<link rel="stylesheet" href="{{ "/assets/css/clean-blog.css, " | prepend: site.baseurl }}"
