# Site settings
title: Thomas Rimlinger
header-img: ./img/saturn.jpeg
email: thomas.rimlinger@icloud.com

url: "https://trimlinger.github.io"
github_username:  trimlinger
linkedin: https://www.linkedin.com/in/thomas-rimlinger-4235051b2

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 6
paginate_path: blog/page:num
excerpt_separator: <!--more-->
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
permalink: /blog/:title
#<link rel="stylesheet" href="{{ "/assets/css/clean-blog.css, " | prepend: site.baseurl }}"
